version: 0.1
env:
  variables:
    S3_BUCKET: "possos-challenge-3"
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod --aot
  post_build:
    commands:
      - aws s3 cp dist s3://possos-challenge-3 --recursive
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: no
